-- DISABLE RLS SEMENTARA UNTUK TESTING
-- Copy paste dan jalankan di Supabase SQL Editor

ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE supervisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE additional_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE schools DISABLE ROW LEVEL SECURITY;