-- TAMBAH KOLOM YANG HILANG DI TABEL SUPERVISIONS
-- Copy paste dan jalankan di Supabase SQL Editor

ALTER TABLE supervisions 
ADD COLUMN IF NOT EXISTS photo1 TEXT,
ADD COLUMN IF NOT EXISTS photo2 TEXT,
ADD COLUMN IF NOT EXISTS teacher_name TEXT,
ADD COLUMN IF NOT EXISTS teacher_nip TEXT,
ADD COLUMN IF NOT EXISTS recommendations TEXT;